export const Users = [
  {
    id: 1,
    profilePicture: '/assets/person/user1.jpeg',
    username: 'Katharina F.',
  },
  {
    id: 2,
    profilePicture: '/assets/person/user2.jpeg',
    username: 'John Doe',
  },
  {
    id: 3,
    profilePicture: '/assets/person/user3.jpeg',
    username: 'Angelika Smith',
  },
  {
    id: 4,
    profilePicture: '/assets/person/user4.jpeg',
    username: 'Elizabeth S.',
  },
  {
    id: 5,
    profilePicture: '/assets/person/user5.jpeg',
    username: 'Oliver',
  },
  {
    id: 6,
    profilePicture: '/assets/person/user6.jpeg',
    username: 'Herald L.',
  },
  {
    id: 7,
    profilePicture: '/assets/person/user7.jpeg',
    username: 'Smith Johns',
  },
  {
    id: 8,
    profilePicture: '/assets/person/user8.jpeg',
    username: 'Lily S.',
  },
  {
    id: 9,
    profilePicture: '/assets/person/user9.jpeg',
    username: 'Barbara',
  },
  {
    id: 10,
    profilePicture: '/assets/person/user10.jpeg',
    username: 'Alexander Wang',
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Look at this!",
    photo: '/assets/post/cat.jpg',
    date: '5 mins ago',
    userId: 1,
    like: 102,
    comment: 23,
  },
  {
    id: 2,
    photo: '/assets/post/auto.jpg',
    date: '15 mins ago',
    userId: 2,
    like: 32,
    comment: 8,
  },
  {
    id: 3,
    desc: 'Every moment is a fresh beginning.',
    photo: 'assets/post/friends.jpg',
    date: '1 hour ago',
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: 'assets/post/food.jpeg',
    date: '4 hours ago',
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: 'assets/post/girl.jpg',
    date: '5 hours ago',
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: 'assets/post/ski.jpeg',
    date: '1 day ago',
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: 'Never regret anything that made you smile.',
    photo: 'assets/post/children.jpeg',
    date: '2 days ago',
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: 'assets/post/relax.jpeg',
    date: '3 days ago',
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: 'Change the world with someone)',
    photo: 'assets/post/wedding.jpeg',
    date: '5 days ago',
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: 'assets/post/horses.jpg',
    date: '1 week ago',
    userId: 10,
    like: 104,
    comment: 12,
  },
];
